---
- hosts: all
  roles:
    - common
    - monitoring

- hosts: standalone
  roles:
    - qdrant-standalone

- hosts: qdrant-distributed
  roles:
    - qdrant-distributed
    - nginx

- hosts: chromadb-servers
  roles:
    - chromadb-standalone
